version: '3.8'

services:
  bot:
    build: .
    container_name: polytech_bot
    restart: always
    env_file:
      - .env
    environment:
      # Переопределяем хост БД, чтобы он указывал на сервис db
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot-network

  db:
    image: mysql:8.0
    container_name: polytech_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Пароль root для MySQL
      MYSQL_DATABASE: ${DB_NAME}               # Имя БД для создания
      MYSQL_USER: ${DB_USER}                   # Имя пользователя
      MYSQL_PASSWORD: ${DB_PASSWORD}           # Пароль пользователя
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bot-network

volumes:
  mysql_data:

networks:
  bot-network:
    driver: bridge 